//
//  Neighborhoodpanel.h
//  harborpoint
//
//  Created by Evan Buxton on 4/21/16.
//  Copyright (c) 2016 neoscape. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface Neighborhoodpanel : NSObject

// Drawing Methods
+ (void)drawMappanelWithPop: (NSString*)pop inc: (NSString*)inc age: (NSString*)age title: (NSString*)title;

@end
